### PR TITLE
More Python 3 fixes

### PR DESCRIPTION
**Pull request by taion**
Replaces #7

### CODE REVIEW

**Comment by cancan101** [comment]
Scipy is needed by skimage

**Comment by taion** [comment]
And we still have it: https://github.com/4Catalyzer/nolearn_utils/pull/8/files#diff-b4ef698db8ca845e5845c4618278f29aR23

It just shouldn't be explicitly listed if it's a normal transitive dependency.

**Comment by cancan101** [comment]
Does this still work on py27?

**Comment by taion** [comment]
Why wouldn't it? The tests still pass, anyway.

**Review by cancan101 — APPROVED** [review]

**Pull request merged**
